### ISSUE TITLE
alert box doesn't hide

### ISSUE THREAD

**Issue by prakharsingh** [tomchentw/react-toastr#10]
I've come across this issue while using react-toastr in my application that if the alertbox is going to dismiss automatically after pre defined interval and I hover on it at that particular moment then it stucks and won't clear neither by itself nor using clear() method given for clearing alerts. Please fix this as soon as possible.

**Comment by tomchentw** [comment]
Closed by 6879a76ba02ed0ebd3149f0a6f6715b4bb1c483e

**Comment by prakharsingh** [comment]
Is it fixed?

**Comment by tomchentw** [comment]
Would you like to try it with latest version?

**Comment by prakharsingh** [comment]
Yeah Sure.
