### ISSUE TITLE
Not closing after timeout 

### ISSUE THREAD

**Issue by amit-mn** [tomchentw/react-toastr#107]
I have using this in my project, but toastr is not closing after timeout. And also close button not working.
I am using react@15.6.1 and react-toastr@2.8.2

**Comment by MickWang** [comment]
use react-toastr@2.6.0 and it works.

**Comment by amit-mn** [comment]
Not working with react-toastr@2.6.0 also. Same issue coming.

**Comment by jdc91** [comment]
Why is this issue happening?

**Comment by jdc91** [comment]
Found the reason!
You have to include "animate.min.css" as well as toastr.min.css

  ```
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.3/toastr.min.css">
```
