### ISSUE TITLE
Bump the version that supports react 16 to 3.0 for backwards compatibility

### ISSUE THREAD

**Issue by corviday** [tomchentw/react-toastr#128]
I'm working on a project that uses React 0.14 and version 1.* of [react-bootstrap-table](https://github.com/AllenFang/react-bootstrap-table). React-bootstrap-table ^1.6 [depends on version ^2.3.0 of react-toastr](https://github.com/AllenFang/react-bootstrap-table/blob/dddfdc72d2c290a4f23b0bf86c7fd7836265aad0/package.json).

The [change to package.json](https://github.com/tomchentw/react-toastr/commit/89d8290d0af6b88b4ec7330c05f7948f64521b1d#diff-b9cfc7f2cdf78a7f4b91a753d10865a2) that changed the peer dependency from React `^0.14.0 || ^15.0.0` to React `^15.0.0 || ^16.0.0` means my React 0.14 / react-bootstrap-table ^1.5.0 / react-toastr ^2.1.0 project no longer builds correctly. 

Could you please make the switch from peer dependency React 0.14 | |15 to 15 | | 16 in a new major version (3.0 instead of 2.9.4) so older modules or projects using version 2.* of react-toastr with React 0.14 have backwards compatibility?

**Comment by tomchentw** [comment]
Released [v2.9.5](https://github.com/tomchentw/react-toastr/releases/tag/v2.9.5)
