### ISSUE TITLE
Looking for maintainer?

### ISSUE THREAD

**Issue by sumitparakh** [tomchentw/react-toastr#143]
Hi @tomchentw, 

This is a great library but not updated since 6-7 years. I am willing to be helping you on maintaining this and taking this forward.

**Comment by tomchentw** [comment]
[The behavior of posting this in non related threads](https://github.com/ChhoeTaigi/next/issues/1) is rude and is NOT welcomed in the open source community.

This repository is not looking for any maintainers, nor is this actively maintained.
