### ISSUE TITLE
classSet deprecated

### ISSUE THREAD

**Issue by antoineverger** [tomchentw/react-toastr#19]
Hi, 

we get this warning while using your library : 

"Warning: React.addons.classSet will be deprecated in a future version. See http://fb.me/react-addons-classset"

It seems that classSet is used in ToastMessage.

Hope that helps,

Regards,

Antoine

**Comment by L8D** [comment]
Shouldn't this be closed?

**Comment by tomchentw** [comment]
Released as [v1.5.0](https://github.com/tomchentw/react-toastr/releases/tag/v1.5.0), close now. Thanks @L8D

**Comment by antoineverger** [comment]
Great ! Thansk
