### ISSUE TITLE
HTML in title / message

### ISSUE THREAD

**Issue by ibiza240** [tomchentw/react-toastr#28]
Hi,

first, great work - thank you very much!

Is there a way to insert HTML in the title or description ?

E.g. I would like to use `<br />` or `<p></p>` to make my toast more readable.

Thanks!

**Comment by jerairrest** [comment]
Could you use CSS to produce the same effect?

**Comment by kriegerd** [comment]
+1 to this enhancement. 
Great work!

**Comment by simoneb** [comment]
Any reason why this isn't supported? It is possible by default with toastr.

**Comment by tomchentw** [comment]
Guys, feel free to raise up a PR for this. I'll review it and close this ASAP.

**Comment by BerkeleyTrue** [comment]
This is currently possible my making the message/title a react element instead of a string

**Comment by simoneb** [comment]
@BerkeleyTrue wow, that actually works, great idea!

**Comment by tomchentw** [comment]
@BerkeleyTrue @simoneb mind to submit a PR to update examples to include this scenario :)

**Comment by simoneb** [comment]
@tomchentw  https://github.com/tomchentw/react-toastr/pull/55

**Comment by tomchentw** [comment]
Closed via #55
