### ISSUE TITLE
react-dom dependency not properly declared

### ISSUE THREAD

**Issue by basilveerman** [tomchentw/react-toastr#40]
Current requirement as a development dependency results in errors when required by other packages:

> ERROR in ./~/react-bootstrap-table/~/react-toastr/lib/ToastMessage/animationMixin.js
Module not found: Error: Cannot resolve module 'react-dom' in /home/bveerman/code/climate-explorer/client/node_modules/react-bootstrap-table/node_modules/react-toastr/lib/ToastMessage
 @ ./~/react-bootstrap-table/~/react-toastr/lib/ToastMessage/animationMixin.js 5:15-35

Changes introduced in e8b71523c64f152f257213c0a08a1ff5f34d11a4 require react-dom as a dependency.

**Comment by jerairrest** [comment]
Good catch. You are correct. ReactDOM was introduced in React 0.14 as a dependency since React.render is now deprecated. React-dom should be a peer dependency. I'll get a PR request for this asap.

Jer

**Comment by tomchentw** [comment]
Thanks the PR #41 by @jerairrest ! Current up to date version is [v2.2.2](https://github.com/tomchentw/react-toastr/blob/master/CHANGELOG.md#222-2015-11-02)
