### ISSUE TITLE
TypeError: Cannot read property 'ToastContainer' of undefined(…)

### ISSUE THREAD

**Issue by luqin** [tomchentw/react-toastr#42]

**Comment by tomchentw** [comment]
More details?

**Comment by luqin** [comment]
```
export default {
  ToastContainer,
  ToastMessage,
  ToastMessageList,
};
```

**Comment by iamyardem** [comment]
another error message while compiling project is 

ERROR in ./~/react-toastr/lib/ToastMessage/jQueryMixin.js
Module not found: Error: Cannot resolve module 'jquery' in \node_modules\react-toastr\lib\ToastMessage
 @ ./~/react-toastr/lib/ToastMessage/jQueryMixin.js 9:14-31

**Comment by tomchentw** [comment]
@luqin this is exported as ES2015 module. It make no sense to export default with an object. https://github.com/tomchentw/react-toastr/blob/97e046bcf73694ecdd170c229a08700e1e9a3840/lib/index.js

**Comment by tomchentw** [comment]
@iamyardem @luqin sorry guys, I think I accidentally introduce new commits in a patch bump. See [CHANGELOG.md for v2.2.1](https://github.com/tomchentw/react-toastr/blob/master/CHANGELOG.md#221-2015-11-02) here. I'll unpublished it from npm now.

**Comment by tomchentw** [comment]
[v2.2.2](https://github.com/tomchentw/react-toastr/releases/tag/v2.2.2) published. Sorry again for any inconvenience.

**Comment by iamyardem** [comment]
thanks for fast reply! appreciate it :)
