### ISSUE TITLE
call function on or after dismissal

### ISSUE THREAD

**Issue by markortiz** [tomchentw/react-toastr#46]
How could I call a function after the alert dismiss?

Just like the `onDismiss` event of [react-notification](https://github.com/pburtchaell/react-notification)

**Comment by RangarajKaushikSundar** [comment]
@markortiz In the ToasterContainer.js, there is a handle_toast_on_click() function.

**Comment by markortiz** [comment]
Cool! Thank for your help @RangarajKaushikSundar.
