### ISSUE TITLE
React 15 Support

### ISSUE THREAD

**Issue by staskorz** [tomchentw/react-toastr#47]

**Comment by qakovalyov** [comment]
Please, update as soon as possible ) thanks

**Comment by DimaRGB** [comment]
@qakovalyov +1

**Comment by ksolod** [comment]
+1

**Comment by kscons** [comment]
+1

**Comment by jerairrest** [comment]
See https://github.com/tomchentw/react-toastr/pull/48

**Comment by tomchentw** [comment]
Published [v2.6.0](https://github.com/tomchentw/react-toastr/releases/tag/v2.6.0)

**Comment by qakovalyov** [comment]
thanks ) 👍

**Comment by tomchentw** [comment]
* fixed in 394ef07 for #49 
* marked `v2.6.0` as `deprecated`
* published [v2.6.1](https://github.com/tomchentw/react-toastr/releases/tag/v2.6.1)
