### ISSUE TITLE
prevent duplicates -- issues

### ISSUE THREAD

**Issue by RangarajKaushikSundar** [tomchentw/react-toastr#53]
Although the previous message and the next message is identical, the new toast message renders. Kindly advise.

**Comment by RangarajKaushikSundar** [comment]
Will be resolved when [this](https://github.com/tomchentw/react-toastr/pull/58) is merged with the master.

**Comment by tomchentw** [comment]
Released [v2.8.0](https://github.com/tomchentw/react-toastr/releases/tag/v2.8.0)
