### ISSUE TITLE
onClose callback

### ISSUE THREAD

**Issue by ryanVincent** [tomchentw/react-toastr#54]
There should be a callback made available on close that is triggered when the close button is pressed so that you can perform some action in response to the toast being closed.

**Comment by RangarajKaushikSundar** [comment]
@ryanVincent  Hi Ryan, I believe there is an option to pass a function through props that will be invoked during toaster close. If you are unable to use the functionality, I would strongly recommend you to fork the code and make the necessary changes. @tomchentw  has done a great job with the code documentation/commenting, the code is clean and easily readable.

**Comment by itwasmattgregg** [comment]
@RangarajKaushikSundar can you point to this prop? I don't see it anywhere in the code other than `handleRemove()` in the ToastrMessage.
