### ISSUE TITLE
Loose jquery

### ISSUE THREAD

**Issue by mschipperheyn** [tomchentw/react-toastr#6]
I like the component, but jquery is a showstopper. Seems like a huge amount of overhead for this component. It would make more sense to use lodash for some of the convenience methods.

**Comment by tomchentw** [comment]
Me too. As my first attempt to write React component and maintain the same interface as `toaster.js` does, I choose `jQuery` only for it's animation methods (`show/nide`). Can `lodash` accomplish those animation efferts?

**Comment by mschipperheyn** [comment]
No, I don't think lodash does that but it should be very simple to just implement that using either a separate stylesheet or "native" react styles.

**Comment by tomchentw** [comment]
Agreed. I was thinking if `animate.css` would help. We should modify some internal APIs to adapt animation callbacks but I believe it's doable.

**Comment by mschipperheyn** [comment]
Yeah, the animations should be pretty straight forward. You might consider just including the ones you need in a custom css. You might also need some abstraction/shim to help you deal with the post animation cleanup onTransitionEnd. So perhaps that library can help you with that. But the code in this case is also straightforward.

**Comment by Janekk** [comment]
Hi, I created a PR with pure css animations: https://github.com/tomchentw/react-toastr/pull/9

**Comment by tomchentw** [comment]
Thanks @Janekk , close now.
