### ISSUE TITLE
Usage documentation question

### ISSUE THREAD

**Issue by Najdan** [tomchentw/react-toastr#61]
Hello,

I have question about initial setup. If react-toastr is installed via npm install is it enough to be able to use component or do I still need to include css and js as it says in usage on readme.md

> Usage
> 
> This module requires to be bundled with webpack/browserify and loads react/addons internally.
> You'll need to download animate.css from here Animate @github
> 
> Link to css/js properly..
> 
> ```
> <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css">
> <link rel="stylesheet" href="/static/dist/css/animate.css">
> 
> <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
> ```
> WIP: release a UMD version via bower/components.
> 
> Then:
> 
> ```
> var ReactToastr = require("react-toastr");
> var {ToastContainer} = ReactToastr; // This is a React Element.
> // For Non ES6...
> // var ToastContainer = ReactToastr.ToastContainer;
> var ToastMessageFactory = React.createFactory(ReactToastr.ToastMessage.animation);
> 
>   // In a react component:
>   render () {
>     return (
>       <div>
>         <ToastContainer ref="container"
>                         toastMessageFactory={ToastMessageFactory}
>                         className="toast-top-right" />
>         <button onClick={this.addAlert}>GGininder</button>
>       </div>
>     );
>   }
> ```
> 
> 

For me it works without **toastr.min.css**, **animate.css** and **toastr.min.js** included in **index.html** but I'm not sure if it's right way to do it.
I'm using **gulp**.

Best regards,
Najdan

**Comment by RangarajKaushikSundar** [comment]
@Najdan `toastr.min.css` provides you with the ability to customize the notification. By changing the className, you will be easily able to re position the toastr. It is recommended to include the files. Kindly share if all the functionalities of the toastr, including the animations are intact despite not including the file.
