### ISSUE TITLE
Warning by props

### ISSUE THREAD

**Issue by erikaperugachi** [tomchentw/react-toastr#68]
"Warning: Unknown props `toastMessageFactory`, `toastType`, `preventDuplicates`, `newestOnTop` on <div> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop

**Comment by anhkhoi** [comment]
Duplicated with https://github.com/tomchentw/react-toastr/issues/63

**Comment by tomchentw** [comment]
Closed by #67

**Comment by tomchentw** [comment]
Released [v2.8.0](https://github.com/tomchentw/react-toastr/releases/tag/v2.8.0)

**Comment by AllenFang** [comment]
thanks for fixing :)
