### ISSUE TITLE
Update published build with latest lodash version (due to lodash issue #1798)

### ISSUE THREAD

**Issue by fedulovivan** [tomchentw/react-toastr#74]
Hello!

Faced with nasty issue, originally caused by https://github.com/lodash/lodash/issues/1798, which promised to be fixed in [4.14.0](https://github.com/lodash/lodash/wiki/Changelog#v4140) lodash release.

It causes overwriting of global 'window.\_' with imported version of lodash (even packed via babel). In my case this is legacy application, and global '\_' is already occupied by underscore.

**Comment by tomchentw** [comment]
We use semver `^` operator so this is not needed.
https://github.com/tomchentw/react-toastr/blob/b0fadc4afd51d381b983ce499d6cdfb667d319d2/package.json#L89
