### ISSUE TITLE
Mousemove stops hideAnimation

### ISSUE THREAD

**Issue by KochiyaOcean** [tomchentw/react-toastr#76]
Steps to reproduce:
 - Use a hideAnimation with movement such as fadeOutDown
 - Toggle a toast
 - Click to dismiss it
 - Move mouse out of toast then quickly move into it again
 - The hideAnimation is interrupted and return to the origin position.

![yxvhwsdiud](https://cloud.githubusercontent.com/assets/8194131/17940019/c0440d46-6a5f-11e6-896e-e74ccf7cb730.gif)

**Comment by RangarajKaushikSundar** [comment]
@KochiyaOcean  Thank you for the query. I believe this is an intended feature and can be very helpful.

Explanation: If the user has hovered over a toast notification, then we can assume that the user is currently reviewing it. If the user clicks on it by mistake or hovers "in and out" which would close the toast notification, by focusing (hovering in) on the toast, it will not be closed until the user has completely moved out from it.

**Comment by KochiyaOcean** [comment]
I got it. Thanks for your explanation :-)
