### ISSUE TITLE
How to set toast options?

### ISSUE THREAD

**Issue by mirko77** [tomchentw/react-toastr#83]
Hi there, 

how do I change the toast options?

I tried:

```
showToastSuccess(message) {
        this.refs.container.success(message, '', {
            closeButton: true,
            timeOut: 3000,
            extendedTimeOut: 0,
            showMethod: 'fadeIn',
            hideMethod: 'fadeOut',
            preventDuplicates: true
        });
    }
```

but the animation is always the bouncing one, not the fade one. 

Timeout options seem to work, though.

**Comment by RangarajKaushikSundar** [comment]
@mirko77 When you mount the toaster, if you use this -
```var ToastMessageFactory = React.createFactory(ReactToastr.ToastMessage.animation)```
It will not work. You have to use 
```var ToastMessageFactory = React.createFactory(ReactToastr.ToastMessage.jQuery)```

Hope this was helpful!
Kaushik.

**Comment by mirko77** [comment]
Thanks @RangarajKaushikSundar , I suppose that will require jQuery as a dependency defined somewhere?

Otherwise, I get `jQueryMixin.js:74 Uncaught (in promise) ReferenceError: jQuery is not defined(…)`

I'd rather not load jQuery only to change the animation, so am I left with tweaking the `animationMixin.js` file? Any better option?

**Comment by mirko77** [comment]
Thanks @RangarajKaushikSundar , I suppose that will require jQuery as a dependency defined somewhere?
Otherwise, I get jQueryMixin.js:74 Uncaught (in promise) ReferenceError: jQuery is not defined(…)

also, I am using the latest React with ES6 therefore no mixins, no getDefaultProps etc...

**Comment by mirko77** [comment]
I solved it passing:
```
showAnimation: 'animated fadeIn',
hideAnimation: 'animated fadeOut'
```
