### ISSUE TITLE
React 15.4.0 is not supporting import `react/lib/*`

### ISSUE THREAD

**Issue by pedramphp** [tomchentw/react-toastr#86]
React 15.4.0 is not supporting import `react/lib/*` or `react-dom/lib/*` anymore.

React package and browser build no longer "secretly" includes React DOM.
Release wiki: https://github.com/facebook/react/releases/tag/v15.4.0
Dan Abramov tweet: https://twitter.com/dan_abramov/status/798926305030877184

Please review the code in the `animationMixin.js`
`animationMixin.js`: https://github.com/tomchentw/react-toastr/blob/b0fadc4afd51d381b983ce499d6cdfb667d319d2/lib/ToastMessage/animationMixin.js#L7

**Comment by tomchentw** [comment]
Released [v2.9.1](https://github.com/tomchentw/react-toastr/releases/tag/v2.9.1)
