### ISSUE TITLE
ToastMessage of undefined

### ISSUE THREAD

**Issue by mohamedtijani** [tomchentw/react-toastr#90]
Uncaught TypeError: Cannot read property 'ToastMessage' of undefined ??

import ReactToastr , {ToastContainer} from 'react-toastr';
let ToastMessageFactory = React.createFactory(ReactToastr.ToastMessage.animation);

**Comment by bsutherland** [comment]
Try this:

```es6
import { ToastContainer, ToastMessage } from 'react-toastr';

const ToastMessageFactory = React.createFactory(ToastMessage.animation);
```

**Comment by mohamedtijani** [comment]
Thanks
