### ISSUE TITLE
Accessing PropTypes via the main React package is deprecated

### ISSUE THREAD

**Issue by mikecousins** [tomchentw/react-toastr#94]
I opened a pull request to fix this error: https://github.com/tomchentw/react-toastr/pull/93

![image](https://cloud.githubusercontent.com/assets/725614/25116999/3c1f580e-23cd-11e7-847b-5da933741ef7.png)

**Comment by tomchentw** [comment]
Released [v2.9.0](https://github.com/tomchentw/react-toastr/releases/tag/v2.9.0)
