### ISSUE TITLE
React.createClass is deprecated

### ISSUE THREAD

**Issue by mikecousins** [tomchentw/react-toastr#95]
This is throwing errors in this library. There seems to be two instances of it in your code.

![image](https://cloud.githubusercontent.com/assets/725614/25116992/345bc242-23cd-11e7-9c51-d88a03540e23.png)

**Comment by fenghou1st** [comment]
Same warning here.
This is the best react wrapper of toastr I have seen, I hope to continue using it in the next few years.

**Comment by anhkhoi** [comment]
The same warning for me. It should be fixed.

**Comment by anhkhoi** [comment]
I see two pulled requests but they're not merged yet. #103 #97

**Comment by tomchentw** [comment]
Released [v2.9.0](https://github.com/tomchentw/react-toastr/releases/tag/v2.9.0)
